baseURL = "https://helpfulbadger.github.io/"
DefaultContentLanguage  = "en"
languageCode = "en-us"
title = "Helpful Badger's Blog"
theme = "hugo-future-imperfect-slim"
paginate                = 10
pluralizeListTitles     = false
disableLanguages = [""]

[outputs]
  home = ["html", "json"]

[params]
  enableCDN             = false
  cssFiles              = ["default"]
  jsFiles               = ["default"]
  highlightjs           = false
  highlightjsTheme      = "dracula"
  highlightjsLang       = ["html", "css", "js", "toml"]
  pygmentsCodefences            = true
  pygmentsCodefencesGuessSyntax = true
  pygmentsStyle                 = "dracula"
  viewMorePostsLink     = "/blog/"
  readingTime           = true
  socialShare           = ["twitter", "facebook", "reddit", "linkedin", "pinterest", "email"]

  [params.meta]
    description         = "A theme by HTML5 UP, ported by Julio Pescador. Slimmed and enhanced by Patrick Collins. Multilingual by StatnMap. Powered by Hugo."
    author              = "Helpful Badger"
    favicon             = false
    svg                 = true
    faviconVersion      = "1"
    msColor             = "#ffffff"
    iOSColor            = "#ffffff"

  [params.header]
    navbarTitle         = "Helpful Badger"
    dynamicTitles       = true
    searchMenu          = true
    shareMenu           = true
    languageMenu        = false

  [params.intro]
    header                = "Helpful Badger"
    paragraph             = "Imagining the possibilities"
    rssIntro              = true
    socialIntro           = true
    hideWhenSingleColumn  = true
    alwaysOnHomepage      = false

    [params.intro.pic]
      src                 = "img/main/unsplash_badger_small_2.png"
      shape               = "circle"
      width               = ""
      alt                 = "Helpful Badger in the wild"

  [params.sidebar]
    about               = "Sharing perspectives."
    postAmount          = 5
    categories          = true
    categoriesByCount   = true

  [params.footer]
    rssFooter           = true
    socialFooter        = true

  [params.staticman]
    enabled             = false
    api                 = ""  # No Trailing Slash
    gitProvider         = ""
    username            = ""
    repo                = ""
    branch              = ""

    [params.staticman.recaptcha]
      siteKey           = ""
      encryptedKey      = ""

[menu]

  [[menu.main]]
    name              = "Home"
    identifier        = "home"
    url               = "/"
    pre               = "<i class='fa fa-home'></i>"
    weight            = 1

  [[menu.main]]
    name              = "About"
    identifier        = "about"
    url               = "/about/"
    pre               = "<i class='far fa-id-card'></i>"
    weight            = 2

  [[menu.main]]
    name              = "Blog"
    identifier        = "blog"
    url               = "/blog/"
    pre               = "<i class='far fa-newspaper'></i>"
    weight            = 3

  [[menu.main]]
    name              = "Categories"
    identifier        = "categories"
    url               = "/categories/"
    pre               = "<i class='fas fa-sitemap'></i>"
    weight            = 5

[Languages]

  [Languages.en]
    LanguageCode        = "en"
    LanguageName        = "English"
    weight              = 1

[social]
  # Coding Communities
  github                = "helpfulBadger"
  # Publishing Communities
  wordpress             = ""
  medium                = ""
  # Professional/Business Oriented Communities
  linkedin              = "example"
  # Social Networks

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.parser]
      attribute = true
      autoHeadingID = true
      autoHeadingIDType = "github"
    [markup.goldmark.renderer]
      unsafe = true
      hardWraps = false
      xhtml = false  
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
    style = "dracula"
    tabWidth = 2
  [markup.tableOfContents]
    endLevel = 3
    ordered = false
    startLevel = 1